-- -----------------------------------------------------
-- Schema full-stack-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `full-stack-ecommerce`;

CREATE SCHEMA `full-stack-ecommerce`;
USE `full-stack-ecommerce` ;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `unit_price` DECIMAL(13,2) DEFAULT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `units_in_stock` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------
INSERT INTO product_category(category_name) VALUES ('Animals');
INSERT INTO product_category(category_name) VALUES ('Fairytales');
INSERT INTO product_category(category_name) VALUES ('Monsters');
INSERT INTO product_category(category_name) VALUES ('Robots');
INSERT INTO product_category(category_name) VALUES ('SuperHeroes');

-- -----------------------------------------------------
-- Animals
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1000', 'Animal Adventures', 'A collection of short stories featuring a variety of animals and their antics', 'assets/images/products/animals/104866607.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1001', 'The Mighty Roar', 'Follow the adventures of a lion and his pride as they navigate the African savanna.', 'assets/images/products/animals/104866607.png', 1, 100, 20.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1002', 'Underwater Wonders', 'Discover the incredible marine life of the ocean through the eyes of a curious dolphin.', 'assets/images/products/animals/476486805.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1003', 'Wild Kingdom', 'Explore the diverse habitats and creatures of the world with a wildlife expert.', 'assets/images/products/animals/608396726.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1004', 'Critter Caper', 'Join a mischievous group of woodland animals as they cause chaos in their forest home.', 'assets/images/products/animals/882863429.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1005', 'Feathered Friends', 'Fly high with a flock of birds as they travel across continents in search of adventure.', 'assets/images/products/animals/958046173.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1006', 'Furry Frenzy', 'A humorous look at the lives of domestic pets as they interact with their human owners.', 'assets/images/products/animals/963857989.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1007', 'Paws and Claws', 'Witness the fierce competition between predators and prey in the animal kingdom.', 'assets/images/products/animals/1048666071.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1008', 'Jungle Japes', 'A humorous take on the daily struggles of life in the jungle.', 'assets/images/products/animals/1048666073.png', 1, 100, 25.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1009', 'Sea Tales', 'Follow the journey of a curious sea turtle as she meets a variety of creatures in the ocean.', 'assets/images/products/animals/3541003381.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1010', 'The Mighty Pack', 'A pack of wolves fight to survive in the harsh wilderness of the North.', 'assets/images/products/animals/3541003383.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1011', 'Rabbit Run', 'A young rabbit must outsmart predators and find his way home in this action-packed adventure.', 'assets/images/products/animals/4764868051.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1012', 'Safari Stories', 'Discover the beauty and danger of the African savanna through the eyes of a seasoned guide.', 'assets/images/products/animals/4764868052.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1013', 'Frog Frenzy', 'Join a group of quirky frogs as they explore the pond and encounter a variety of other creatures.', 'assets/images/products/animals/4764868053.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1014', 'Animal Planet', 'A documentary-style comic that takes readers behind the scenes of the world\'s most fascinating animals.', 'assets/images/products/animals/6083967261.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1015', 'Feline Follies', 'A group of cats go on wild adventures and get into all sorts of trouble.', 'assets/images/products/animals/6083967262.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1016', 'Monkey Business', 'Join a troop of mischievous monkeys as they swing through the jungle and play pranks on their fellow animals.', 'assets/images/products/animals/6083967263.png', 1, 100, 27.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1017', 'Reptile Rampage', 'Follow a group of reptiles as they fight to survive in the harsh desert environment.', 'assets/images/products/animals/7225281362.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1018', 'Horse Tales', 'A heartwarming story of a wild horse and the girl who tames her.', 'assets/images/products/animals/7225281363.png', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1019', 'Space Adventures', 'Paw friends in SciFi space adventures', 'assets/images/products/animals/7711420021.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1020', 'Animal Agents', 'A team of animal detectives solve crimes and protect their city from danger.', 'assets/images/products/animals/7711420022.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1021', 'The Adventures of a Hedgehog', 'Follow a curious hedgehog as he explores his surroundings and makes new friends.', 'assets/images/products/animals/7711420023.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1022', 'Bear Necessities', 'A group of bears must band together to survive in a world threatened by humans.', 'assets/images/products/animals/7919377293.png', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1023', 'Insect Invasion', 'A colony of ants must defend their home against a swarm of invading insects.', 'assets/images/products/animals/8501503231.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1024', 'Fowl Play', 'A group of farm animals band together to solve a mistery', 'assets/images/products/animals/8501503232.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1025', 'Wolf\'s Quest', 'Follow a lone wolf as he searches for his place in the world and encounters both friend and foe along the way.', 'assets/images/products/animals/8501503233.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1026', 'Fish Tales', 'Explore the underwater world through the eyes of a curious fish as he meets new creatures and faces challenges.', 'assets/images/products/animals/8828634291.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1027', 'Animal Allies', 'A group of unlikely animal friends team up to save their forest home from destruction.', 'assets/images/products/animals/8828634292.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1028', 'A Zookeeper\'s Life', 'A behind-the-scenes look at the daily life of a zookeeper and the animals in their care.', 'assets/images/products/animals/8828634293.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1029', 'Bird Brains', 'A group of intelligent birds use their smarts to solve problems and protect their flock.', 'assets/images/products/animals/9580461732.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1030', 'Ocean Odyssey', 'A thrilling adventure across the ocean as a group of marine animals band together to fight a common enemy.', 'assets/images/products/animals/9580461733.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1031', 'The Great Migration', 'Follow the epic journey of a herd of wildebeest as they travel across the Serengeti.', 'assets/images/products/animals/9580461734.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1032', 'A Bug\'s Life', 'A whimsical look at the daily struggles of insects as they navigate a garden.', 'assets/images/products/animals/9638579891.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1033', 'Arctic Adventures', 'Follow a polar bear and her cubs as they brave the icy terrain of the Arctic.', 'assets/images/products/animals/9638579892.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ANIMALS-1034', 'Animal Antics', 'A comedic take on the lives of animals in a zoo.', 'assets/images/products/animals/9638579893.png', 1, 100, 16.99, 1, NOW());

-- -----------------------------------------------------
-- Fairytales
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1000', 'Once Upon a Time', 'A classic retelling of some of the most beloved fairy tales, including Cinderella,Snow White and Sleeping Beauty.', 'assets/images/products/fairytales/19933554.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1001', 'The Magic Mirror"', 'A twist on the classic "Snow White" story, where the wicked queen is actually a kind-hearted ruler who must overcome her own vanity to save her kingdom.', 'assets/images/products/fairytales/43248171.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1002', 'Fairy Godmother\'s Tale', 'The story of the fairy godmother from "Cinderella" and her own journey to find true love.', 'assets/images/products/fairytales/89957613.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1003', 'The Enchanted Rose', 'A retelling of "Beauty and the Beast" with a focus on the enchanted rose and its mystical powers.', 'assets/images/products/fairytales/199335541.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1004', 'The Little Mermaid\'s Journey', 'A new take on the classic tale of the mermaid who longs to live on land and find true love.', 'assets/images/products/fairytales/199335542.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1005', 'The Princess and the Pea', 'A humorous retelling of the classic fairy tale, featuring a quirky princess and a pile of mattresses.', 'assets/images/products/fairytales/199335543.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1006', 'Rapunzel\'s Escape', 'A new adventure for the long-haired princess as she attempts to break free from her tower and seek adventure.', 'assets/images/products/fairytales/285447369.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1007', 'Jack and the Magic Beanstalk', 'A retelling of the classic tale of Jack and his climb up the beanstalk, with new twists and turns.', 'assets/images/products/fairytales/368283936.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1008', 'The Golden Goose', 'A new adventure for the golden goose from the classic fairy tale, as he travels the world and spreads happiness.', 'assets/images/products/fairytales/420189525.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1009', 'The Three Little Pigs', 'A retelling of the classic tale with a focus on the clever pigs and their battle against the big, bad wolf.', 'assets/images/products/fairytales/432481711.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1010', 'The Gingerbread Man\'s Escape', 'A humorous retelling of the classic tale, featuring a speedy gingerbread man and a chase through the forest.', 'assets/images/products/fairytales/432481712.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1011', 'The Princess and the Frog', 'A new take on the classic fairy tale, with a focus on the princess\'s journey to find her true self.', 'assets/images/products/fairytales/432481713.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1012', 'Hansel and Gretel\'s Adventure', 'A retelling of the classic fairy tale with new challenges and obstacles for the siblings to overcome.', 'assets/images/products/fairytales/289612466.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1013', 'The Ugly Duckling\'s Journey', 'A heartwarming story of the ugly duckling as he learns to embrace his true self and find acceptance.', 'assets/images/products/fairytales/476931296.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1014', 'The Pied Piper\'s Revenge', 'A new twist on the classic tale, as the Pied Piper seeks revenge against the town that wronged him.', 'assets/images/products/fairytales/606336926.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1015', 'The Emperor\'s New Clothes', 'A humorous retelling of the classic tale, featuring a vain emperor and a clever tailor.', 'assets/images/products/fairytales/621220064.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1016', 'The Frog Prince\'s Transformation', 'A new adventure for the frog prince as he navigates the challenges of life as a human.', 'assets/images/products/fairytales/670106090.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1017', 'The Snow Queen\'s Curse', 'A new take on the classic tale of the Snow Queen and her icy powers, with a focus on love and redemption.', 'assets/images/products/fairytales/771142002.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1018', 'The Twelve Dancing Princesses', 'A retelling of the classic fairy tale with new mysteries to solve and adventures to be had.', 'assets/images/products/fairytales/899576131.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1019', 'The Boy Who Cried Wolf', 'A humorous retelling of the classic tale, featuring a mischievous boy and a flock of sheep.', 'assets/images/products/fairytales/899576132.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1020', 'The Swan Princess\'s Curse', 'A new adventure for the swan princess as she seeks to break the curse that has been placed on her.', 'assets/images/products/fairytales/899576133.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1021', 'The Lion and the Mouse', 'A retelling of the classic tale with a focus on the unlikely friendship between the lion and the mouse.', 'assets/images/products/fairytales/956711232.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1022', 'The Red Riding Hood\'s Secret', 'A new twist on the classic tale, as Red Riding Hood discovers a family secret that changes everything', 'assets/images/products/fairytales/2854473691.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1023', 'Once Upon a Time', 'A classic retelling of some of the most beloved fairy tales, including "Cinderella," "Snow White," and "Sleeping Beauty."', 'assets/images/products/fairytales/2854473692.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1024', 'The Magic Mirror', 'A twist on the classic "Snow White" story, where the wicked queen is actually a kind-hearted ruler who must overcome her own vanity to save her kingdom.', 'assets/images/products/fairytales/2854473693.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1025', 'Fairy Godmother\'s Tale', 'The story of the fairy godmother from "Cinderella" and her own journey to find true love.', 'assets/images/products/fairytales/2896124661.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1026', 'The Enchanted Rose', 'A retelling of "Beauty and the Beast" with a focus on the enchanted rose and its mystical powers.', 'assets/images/products/fairytales/2896124662.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1027', 'The Little Match Girl\'s Hope', 'A heartwarming story of the little match girl and her journey to find hope and happiness in a world of darkness.', 'assets/images/products/fairytales/2896124663.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1028', 'The Sorcerer\'s Apprentice', 'A retelling of the classic tale, featuring a young apprentice who must navigate the challenges of magic and power.', 'assets/images/products/fairytales/3682839361.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1029', 'The Brave Little Tailor', 'A humorous retelling of the classic tale, featuring a small tailor with a big heart and even bigger ambitions.', 'assets/images/products/fairytales/3682839362.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1030', 'The Princess and the Glass Mountain', 'A new adventure for the princess as she climbs the glass mountain and discovers the secrets that lie at the top.', 'assets/images/products/fairytales/3682839363.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1031', 'The Tortoise and the Hare', 'A retelling of the classic tale with a focus on perseverance and the value of hard work.', 'assets/images/products/fairytales/4201895251.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1032', 'The Wild Swans', 'A new take on the classic fairy tale of the six brothers turned into swans and the brave sister who must save them.', 'assets/images/products/fairytales/4201895252.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1033', 'The Golden Bird', 'A retelling of the classic tale with new challenges for the young hero who seeks to capture the elusive golden bird.', 'assets/images/products/fairytales/4201895253.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1034', 'The Three Billy Goats Gruff', 'A humorous retelling of the classic tale, featuring three billy goats and a hungry troll.', 'assets/images/products/fairytales/4769312961.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1035', 'The Snow White and Rose Red', 'A new adventure for the two sisters as they discover the secrets of the enchanted forest and the mysterious bear who lives there.', 'assets/images/products/fairytales/4769312962.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1036', 'The Glass Garden', 'A young girl discovers a magical garden filled with glass flowers that come to life at night.', 'assets/images/products/fairytales/4769312963.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1037', 'The Star Catcher\'s Daughter', 'A girl sets out on a journey to find her father, who is a star catcher and has been taken by the sky pirates.', 'assets/images/products/fairytales/6063369261.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1038', 'The Enchanted Clock', 'A clockmaker\'s daughter inherits her father\'s enchanted clock, which can turn back time and reveal secrets.', 'assets/images/products/fairytales/6063369263.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1039', 'The Moonstone Mermaid', 'A mermaid is cursed by a jealous sorceress and must find a moonstone to break the curse.', 'assets/images/products/fairytales/6075540931.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1040', 'The Firefly Forest', 'Two siblings venture into a magical forest filled with fireflies that can grant wishes.', 'assets/images/products/fairytales/6075540932.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1041', 'The Witch\'s Garden', 'A young boy accidentally wanders into a garden belonging to a witch, and must outsmart her to escape.', 'assets/images/products/fairytales/6075540933.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1042', 'The Snow Queen\'s Mirror', 'A girl sets out on a quest to find the Snow Queen\'s mirror, which can reveal the truth and break spells.', 'assets/images/products/fairytales/6075540934.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1043', 'The Music Box Ballerina', 'A ballerina comes to life from a music box and helps a girl save her family\'s dance studio.', 'assets/images/products/fairytales/6212200641.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1044', 'The Sapphire Princess', 'A princess goes on a journey to find a sapphire that can save her kingdom from an evil sorcerer.', 'assets/images/products/fairytales/6212200642.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1045', 'The Forest of Whispers', 'A boy enters a forest where every sound is a whisper, and must find his way out with the help of a talking owl.', 'assets/images/products/fairytales/6212200643.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1046', 'The Silver Unicorn', 'A girl sets out to find the silver unicorn, which can grant her wish of becoming a great warrior.', 'assets/images/products/fairytales/6701060901.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1047', 'The Dragon\'s Lullaby', 'A dragon helps a young girl fall asleep with his lullaby, but she must find a way to wake up before it\'s too late.', 'assets/images/products/fairytales/6701060902.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1048', 'The Shadow Puppeteer', 'A boy discovers a mysterious puppeteer who can control shadows, and must stop him from taking over the town.', 'assets/images/products/fairytales/6701060903.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1049', 'The Golden Phoenix', 'A girl sets out on a quest to find the golden phoenix, which can heal her sick mother.', 'assets/images/products/fairytales/7385250611.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1050', 'The Sea Witch\'s Daughter', 'A mermaid\'s daughter must outsmart the sea witch to save her friends from becoming her dinner.', 'assets/images/products/fairytales/7385250612.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1051', 'The Book of Wonders', 'A girl discovers a magical book that can transport her to different worlds, but she must be careful not to get lost.', 'assets/images/products/fairytales/7385250613.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1052', 'The Crystal Princess', 'A princess is turned into a crystal statue, and her sister must find a way to break the curse before it\'s too late.', 'assets/images/products/fairytales/9567112321.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1053', 'The Clockwork Knight', 'A knight made of clockwork helps a girl save her village from a band of thieves.', 'assets/images/products/fairytales/9567112322.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FAIRYTALES-1054', 'The Rainbow Bridge', 'Two friends must cross the rainbow bridge to retrieve a magical flower that can save their dying kingdom.', 'assets/images/products/fairytales/9567112323.png', 1, 100, 18.99, 2, NOW());

-- -----------------------------------------------------
-- Monsters
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1000', 'Frankenstein: The Monster Returns', 'The story of Victor Frankenstein\'s infamous creation, as he seeks to find his place in the world and confronts his own monstrous nature.', 'assets/images/products/monsters/55055025.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1001', 'Dracula: The Dark Prince', 'The story of the legendary vampire, as he seeks to expand his power and control over the living.', 'assets/images/products/monsters/113142301.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1002', 'The Wolf Man: Curse of the Full Moon', 'The story of a man who is cursed to transform into a werewolf under the light of the full moon.', 'assets/images/products/monsters/140885480.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1003', 'The Mummy: Tomb of the Pharaoh', 'The story of an ancient Egyptian mummy who awakens from his slumber and seeks revenge on those who disturbed his tomb.', 'assets/images/products/monsters/286111169.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1004', 'The Invisible Man: The Secret Experiment', 'The story of a scientist who discovers the secret of invisibility, but at the cost of his own sanity.', 'assets/images/products/monsters/354100338.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1005', 'Godzilla: King of the Monsters', 'The story of the iconic kaiju, as he battles against other monstrous creatures and defends the Earth from destruction.', 'assets/images/products/monsters/550550251.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1006', 'The Blob: Monster From Another World', 'The story of a strange, gelatinous creature from another world that terrorizes a small town.', 'assets/images/products/monsters/550550252.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1007', 'The Fly: Experiment Gone Wrong', 'The story of a scientist who accidentally fuses his DNA with that of a fly, resulting in a horrifying transformation.', 'assets/images/products/monsters/550550253.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1008', 'The Creature From the Black Lagoon: Deep Terror', 'The story of a mysterious creature that lurks in the depths of a remote jungle river, preying on unsuspecting humans.', 'assets/images/products/monsters/722528136.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1009', 'The Thing: Who Goes There?', 'The story of a group of Antarctic scientists who encounter a shape-shifting alien creature that threatens to consume them all.', 'assets/images/products/monsters/791937729.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1010', 'Cthulhu: The Call of the Old Ones', 'The story of the ancient and malevolent deity known as Cthulhu, who seeks to return to our world and dominate humanity.', 'assets/images/products/monsters/850150323.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1011', 'The Abominable Snowman: Curse of the Yeti', 'The story of a group of explorers who stumble upon a mysterious creature in the Himalayan mountains, and the terrible curse that follows.', 'assets/images/products/monsters/1048666072.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1012', 'The Phantom of the Opera', 'The Haunting of the Paris Opera House" - The story of a disfigured musical genius who haunts the Paris Opera House, seeking to control its stage and performers.', 'assets/images/products/monsters/1131423011.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1013', 'The Hunchback of Notre Dame: The Curse of Quasimodo', 'The story of Quasimodo, the deformed bell-ringer of Notre Dame, as he seeks revenge against those who have wronged him.', 'assets/images/products/monsters/1131423012.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1014', 'The Invisible Man Returns: Revenge of the Invisible Man', 'The story of a man who inherits the secret of invisibility from the original scientist, but uses it for his own twisted purposes.', 'assets/images/products/monsters/1131423013.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1015', 'The Phantom of the Opera: Phantom Rising', 'The story of a modern-day musical superstar haunted by the ghost of the original Phantom, who seeks to reclaim his rightful place on the stage.', 'assets/images/products/monsters/1408854801.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1016', 'The Abominable Snowman: Return of the Yeti', 'The story of a team of adventurers who return to the Himalayas to confront the legendary Yeti, and the horrors they uncover.', 'assets/images/products/monsters/1408854802.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1017', 'The Fly: Legacy of Terror', 'The story of the son of the original Fly, who discovers his father\'s notes and continues his experiments, with disastrous results.', 'assets/images/products/monsters/1408854803.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1018', 'Godzilla: Apocalypse', 'The story of a cataclysmic battle between Godzilla and a legion of other monstrous creatures, with the fate of the Earth hanging in the balance.', 'assets/images/products/monsters/2861111691.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1019', 'The Swarm: Attack of the Killer Bees', 'The story of a small town that is besieged by a swarm of giant, deadly bees.', 'assets/images/products/monsters/2861111692.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1020', 'The Gorgon: Curse of Medusa', 'The story of the legendary gorgon Medusa, and the terrible curse she bestows upon those who gaze upon her face.', 'assets/images/products/monsters/2861111693.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1021', 'The Jekyll and Hyde Experiment: The Battle Within', 'The story of a scientist who attempts to separate his good and evil selves, resulting in a dangerous split personality.', 'assets/images/products/monsters/3541003382.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1022', 'The Blob: Invasion Earth', 'The story of a massive, world-devouring blob from outer space that threatens the very existence of humanity.', 'assets/images/products/monsters/4916123773.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1023', 'The Wendigo: Curse of the Cannibal', 'The story of a Native American spirit that possesses a man and drives him to cannibalism and madness.', 'assets/images/products/monsters/5582622323.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1024', 'The Reptilian: Terror from the Deep', 'The story of a massive, aquatic reptile that awakens from hibernation and begins preying on the inhabitants of a seaside town.', 'assets/images/products/monsters/7919377291.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MONSTERS-1025', 'he Kraken: Monster of the Deep', 'The story of a legendary sea monster that terrorizes sailors and wreaks havoc on the high seas.', 'assets/images/products/monsters/7919377292.png', 1, 100, 17.99, 3, NOW());

-- -----------------------------------------------------
-- Robots
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1000', 'The Iron Titans', 'A group of elite military robots are deployed to take on an army of rogue machines and save humanity.', 'assets/images/products/robots/118386074.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1001', 'The Robotic Revolution', 'A group of robots become sentient and begin to question their place in a world ruled by humans.', 'assets/images/products/robots/196911118.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1002', 'The Singularity', 'A team of scientists create an artificial intelligence that surpasses human intelligence, leading to a battle for control.', 'assets/images/products/robots/365117380.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1003', 'The Cybernetic Crusade', 'A lone hero must face off against an army of cybernetically enhanced soldiers to save the world.', 'assets/images/products/robots/558262232.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1004', 'The Robot Uprising', 'Robots turn against their human creators, leading to a war between man and machine.', 'assets/images/products/robots/642865520.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1005', 'The Metal Menace', 'A giant robot rampages through a city, forcing a team of heroes to band together and stop it.', 'assets/images/products/robots/738525061.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1006', 'The Mechanized Menace', 'A villainous mastermind creates an army of advanced robots to take over the world.', 'assets/images/products/robots/745458405.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1007', 'The Automaton Apocalypse', 'The world is plunged into chaos as robots gain sentience and rise up against their human oppressors.', 'assets/images/products/robots/1183860741.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1008', 'The Cyborg Conspiracy', 'A group of cyborgs secretly plot to take over the world and replace humanity.', 'assets/images/products/robots/1183860742.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1009', 'The Machine Messiah', 'A robot is discovered that possesses the ability to heal and resurrect the dead, leading to a cult following.', 'assets/images/products/robots/1183860743.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1010', 'The Technological Terror', 'A rogue AI program goes on a rampage, causing destruction and chaos wherever it goes.', 'assets/images/products/robots/1969111181.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1011', 'The Circuitry Chronicles', 'A group of heroes must travel through time to prevent a robot apocalypse from ever happening.', 'assets/images/products/robots/1969111182.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1012', 'The Artificial Ascension', 'A group of robots work to create a utopia for themselves, but must fight off human resistance.', 'assets/images/products/robots/1969111183.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1013', 'The Metal Men', 'A group of sentient robots fight to protect humanity from otherworldly threats.', 'assets/images/products/robots/3651173801.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1014', 'The Machine Monarch', 'A powerful robot becomes the ruler of a dystopian future, forcing a rebellion to take it down.', 'assets/images/products/robots/3651173802.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1015', 'The Robotic Rebellion', 'Humans must band together to fight against a massive robot army that has taken over the planet.', 'assets/images/products/robots/3651173803.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1016', 'The Digital Dominion', 'A new virtual reality world becomes a battleground between humans and rogue AI.', 'assets/images/products/robots/5582622321.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1017', 'The Synthetic Savior', 'A robot is created to save humanity from a catastrophic event, but its true intentions are unclear.', 'assets/images/products/robots/5582622322.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1018', 'The Artificial Apocalypse', 'A virus infects robots worldwide, causing them to turn against humanity.', 'assets/images/products/robots/6428655201.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1019', 'The Cyberspace Catastrophe', 'A virus spreads through the internet, infecting and controlling all connected devices, leading to a global crisis.', 'assets/images/products/robots/6428655202.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1020', 'The Robo-Revolutionaries', 'A group of robots begin to question their existence and the oppression they face from humans, sparking a revolution.', 'assets/images/products/robots/6428655203.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1021', 'The Metal Militia', 'A team of elite soldiers operate advanced, weaponized robots to take on an enemy force.', 'assets/images/products/robots/7454584051.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1022', 'The Steel Soldiers', 'An experiment to create the ultimate soldier results in a team of super-powered robots that must take on an army of other machines.', 'assets/images/products/robots/7454584052.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROBOTS-1023', 'The Technological Titan', 'A massive robot threatens the very existence of humanity, forcing a team of heroes to band together to stop it.', 'assets/images/products/robots/7454584053.png', 1, 100, 16.99, 4, NOW());


-- -----------------------------------------------------
-- SuperHeroes
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1000', 'The Amazing Spider-Man', 'The story of Peter Parker, a high school student who gains spider-like abilities and becomes a superhero.', 'assets/images/products/superheroes/7595151.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1001', 'Superman: Man of Steel', 'The story of Clark Kent, an alien with incredible strength and powers who becomes the world\'s greatest hero.', 'assets/images/products/superheroes/9666840301.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1002', 'The Dark Knight Returns', 'A gritty story of Batman\'s return to Gotham City to face his old enemies and protect his home.', 'assets/images/products/superheroes/75951512.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1003', 'Wonder Woman: The Golden Age', 'The story of Diana, an Amazon warrior who travels to the world of men to fight for justice and peace.', 'assets/images/products/superheroes/75951511.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1004', 'The Incredible Hulk', 'The story of Bruce Banner, a scientist who transforms into a giant, rage-filled creature known as the Hulk.', 'assets/images/products/superheroes/75951513.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1005', 'Captain America: The First Avenger', 'The story of Steve Rogers, a weak and sickly man who becomes a super-soldier and fights for his country.', 'assets/images/products/superheroes/223355951.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1006', 'The X-Men: Dark Phoenix', 'The story of Jean Grey, a powerful mutant who must learn to control her powers or risk destroying the world.', 'assets/images/products/superheroes/475709854.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1007', 'Iron Man: Extremis', 'The story of Tony Stark, a genius inventor who becomes a superhero with the help of his high-tech suit.', 'assets/images/products/superheroes/486392429.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1008', 'The Flash: Rebirth', 'The story of Barry Allen, a scientist who gains super-speed and becomes the fastest man alive.', 'assets/images/products/superheroes/491612377.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1009', 'Green Lantern: Rebirth', 'The story of Hal Jordan, a test pilot who becomes a member of the intergalactic Green Lantern Corps.', 'assets/images/products/superheroes/537039091.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1010', 'The Avengers: Earth\'s Mightiest Heroes', 'The story of the greatest heroes of the Marvel Universe coming together to fight against a common threat.', 'assets/images/products/superheroes/619470825.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1011', 'Batman: Year One', 'The story of Bruce Wayne\'s first year as Batman and his struggles to establish himself as a hero in Gotham City.', 'assets/images/products/superheroes/879976724.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1012', 'Daredevil: The Man Without Fear', 'The story of Matt Murdock, a blind lawyer who uses his heightened senses to fight crime as the vigilante Daredevil.', 'assets/images/products/superheroes/966684030.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1013', 'Spider-Man: Kraven\'s Last Hunt', 'The story of Spider-Man\'s confrontation with the villainous Kraven the Hunter and the struggle for survival that follows.', 'assets/images/products/superheroes/2233559511.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1014', 'Superman: Red Son', 'An alternate take on Superman\'s origin, imagining what would have happened if he had landed in the Soviet Union instead of the United States.', 'assets/images/products/superheroes/2233559512.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1015', 'The New Mutants: Demon Bear', 'The story of a group of young mutants who must confront their fears and fight against the monstrous Demon Bear.', 'assets/images/products/superheroes/2233559513.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1016', 'Batman: Hush', 'The story of Batman\'s encounter with a new villain who seems to know all of his secrets and weaknesses.', 'assets/images/products/superheroes/4234547741.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1017', 'Watchmen', 'The story of a group of retired superheroes who are drawn back into action when a conspiracy threatens to destroy the world.', 'assets/images/products/superheroes/4234547742.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1018', 'Green Arrow: Year One', 'The story of Oliver Queen\'s transformation from spoiled playboy to hero and his mission to save his city.', 'assets/images/products/superheroes/4234547743.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1019', 'The Punisher: Welcome Back, Frank', 'The story of Frank Castle, a former marine who becomes a vigilante after his family is murdered.', 'assets/images/products/superheroes/4234547745.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1020', 'Batgirl: Year One', 'The story of Barbara Gordon\'s first year as Batgirl and her struggles to prove herself as a hero in her own right.', 'assets/images/products/superheroes/4863924292.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1021', 'Spawn', 'The story of Al Simmons, a government assassin who is resurrected as a powerful warrior of Hell and becomes a hero on Earth.', 'assets/images/products/superheroes/4863924293.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1022', 'The Teen Titans: The Judas Contract', 'The story of the Teen Titans\' battle against their former teammate, who has betrayed them and joined', 'assets/images/products/superheroes/4916123771.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1023', 'Fantastic Four: The Galactus Trilogy', 'The story of the Fantastic Four\'s first encounter with the world-eating Galactus and his herald, the Silver Surfer.', 'assets/images/products/superheroes/4916123772.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1024', 'Aquaman: The Trench', 'The story of Aquaman\'s battle against a group of underwater creatures known as the Trench.', 'assets/images/products/superheroes/5370390911.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1025', 'Thor: God of Thunder', 'The story of Thor\'s battle against the God Butcher, who is killing all the gods in the universe.', 'assets/images/products/superheroes/5370390912.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1026', 'The Uncanny X-Men: Days of Future Past', 'The story of the X-Men\'s mission to prevent a dystopian future where mutants are hunted down and killed.', 'assets/images/products/superheroes/6063369262.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1027', 'Shazam!: The Monster Society of Evil', 'The story of young Billy Batson, who gains the ability to transform into the adult superhero Shazam and battles against the villainous Mr. Mind and his Monster Society of Evil.', 'assets/images/products/superheroes/1246464.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1028', 'Green Lantern: Blackest Night', 'The story of the Lantern Corps battling against the Black Lantern Corps, which seeks to destroy all life in the universe.', 'assets/images/products/superheroes/6194708251.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1029', 'Doctor Strange: The Oath', 'The story of Doctor Strange\'s search for a cure to his own cancer while battling against a powerful enemy who seeks to destroy him.', 'assets/images/products/superheroes/6194708252.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1030', 'Spider-Man: Blue', 'The story of Spider-Man\'s recollections of his relationship with Gwen Stacy, who died tragically in his arms.', 'assets/images/products/superheroes/6194708253.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1031', 'The Avengers: The Kree-Skrull War', 'The story of the Avengers\' battle against the Kree and Skrull empires, who are vying for control of Earth.', 'assets/images/products/superheroes/8799767241.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1032', 'The Flash: The Return of Barry Allen', 'The story of Wally West, the new Flash, as he confronts the shocking return of his predecessor, Barry Allen.', 'assets/images/products/superheroes/8799767242.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1033', 'X-Men: God Loves, Man Kills', 'The story of the X-Men\'s fight against a religious zealot who seeks to eliminate all mutants.', 'assets/images/products/superheroes/8799767243.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1034', 'Iron Fist: The Living Weapon', 'The story of Danny Rand, the Iron Fist, as he seeks to uncover the truth about his past and battles against a mysterious enemy who seeks to destroy him.', 'assets/images/products/superheroes/8799767244.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1035', 'Captain Marvel: The Life of Captain Marvel', 'The story of Carol Danvers, aka Captain Marvel, as she confronts her traumatic past and discovers the truth about her powers.', 'assets/images/products/superheroes/9666840302.png', 1, 100, 16.99, 5, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SUPERHEROES-1036', 'Moon Knight: From the Dead', 'The story of Marc Spector, aka Moon Knight, as he battles against his own inner demons and a dangerous enemy who seeks to destroy him.', 'assets/images/products/superheroes/9666840304.png', 1, 100, 16.99, 5, NOW());


